@startuml
class CharacterMovementHelp {
    - m_XROrigin : XROrigin
    - m_CharacterController : CharacterController
    - driver : CharacterControllerDriver
    - Update() : void
    # <<virtual>> UpdateCharacterController() : void
}
MonoBehaviour <|-- CharacterMovementHelp
@enduml
