@startuml
class EnemySpawn {
    + enemy : GameObject
    + spawnChance : int
    + spawnInterval : float
    - spawnedEnemy : GameObject
    - timePassedSinceLastSpawnTry : float = 0
    - Update() : void
    - SpawnEnemy(position:Vector3) : void
}
MonoBehaviour <|-- EnemySpawn
@enduml
