@startuml
class HealthBarPlayer {
    + slider : Slider
    + gradient : Gradient
    + fill : Image
    + SetMaxHealth() : void
    + SetHealth(playerHealth:float) : void
}
MonoBehaviour <|-- HealthBarPlayer
@enduml
