@startuml
!include .\\LevelChange.puml
!include .\\Boss\AI_Boss.puml
!include .\\Boss\animatorController.puml
!include .\\Boss\BossHitbox.puml
!include .\\Boss\BossHitRange.puml
!include .\\Boss\BossStats.puml
!include .\\Boss\StartBossFight.puml
!include .\\GarbagePathFinding\Animation.puml
!include .\\GarbagePathFinding\EaseInOut.puml
!include .\\GarbagePathFinding\Grid.puml
!include .\\GarbagePathFinding\Node.puml
!include .\\GarbagePathFinding\Pathfinding.puml
!include .\\GarbagePathFinding\RemoveAnimationScript.puml
!include .\\NPCs\AI_NPC.puml
!include .\\NPCs\EnemySpawn.puml
!include .\\NPCs\NavMeshTurn.puml
!include .\\NPCs\NPCDespawn.puml
!include .\\Player\CharacterMovementHelp.puml
!include .\\Player\CollectGarbage.puml
!include .\\Player\SetNewCamera.puml
!include .\\SoundScript\GrabSword.puml
!include .\\SoundScript\PressButtonStory.puml
!include .\\UI\HealthBarBoss.puml
!include .\\UI\HealthBarPlayer.puml
!include .\\UI\IncreaseScore.puml
!include .\\UI\PlayerStats.puml
!include .\\UI\Timer.puml
@enduml
